branch-defaults:
  default:
    environment: udagram-app
  main:
    environment: udagram-app
deploy:
  artifact: www/Archive.zip
environment-defaults:
  udagram-app:
    branch: null
    repository: null
global:
  application_name: udagram-api
  default_ec2_keyname: aws-eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
